from . import fuel_station
from . import fuel_pump
from . import fuel_nozzle
from . import fuel_tank
from . import fuel_shift
from . import fuel_meter_reading
from . import fuel_dip_reading
from . import fuel_license
from . import fuel_dashboard
