from . import fuel_station
from . import fuel_pump
from . import fuel_nozzle
from . import fuel_tank
from . import fuel_shift
from . import fuel_meter_reading
from . import fuel_dip_reading
from . import fuel_license
from . import fuel_dashboard
from . import fuel_purchase
from . import fuel_collection
from . import fuel_receipt
from . import fuel_tank_replenishment
from . import fuel_meter_correction
from . import res_users
from . import fuel_expense